### ISSUE TITLE
There is a problem running the code.

### ISSUE THREAD

**Issue by momo-xiaoyi** [cassidylaidlaw/boltzmann-policy-distribution#1]
In the "Calculating the BPD" section. The command is the following:

`python -m maxent_policy_rl.experiments.train_overcooked with run="bpd" num_workers=25 num_training_iters=2000 layout_name="cramped_room" temperature=0.1 prior_concentration=0.2 reward_shaping_horizon=20000000 latents_per_iteration=250  share_dense_reward=True train_batch_size=100000 discriminate_sequences=True max_seq_len=10 entropy_coeff_start=0 entropy_coeff_end=0 latent_size=1000 sgd_minibatch_size=8000 use_latent_attention=True`

However, there is no file named maxent_policy_rl.

**Comment by momo-xiaoyi** [comment]
The link of the pretrained models is also invalid.

**Comment by cassidylaidlaw** [comment]
Hello, thank you for your interest in the code! I just updated the README, it should actually be `python -m bpd.experiments.train_overcooked ...`. `maxent_policy_rl` was an old package name. I also believe I've fixed the download link for the pretrained models. Let me know if this fixes your problems.

**Comment by momo-xiaoyi** [comment]
fixed now！
